### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by JMarts32** [ISIS3510-Seccion-3-Grupo-32/Documentation#4]
The classes that are going to be used in the app might be defined in a diagram. This diagram is going to be an image in the wiki

**Comment by JMarts32** [comment]
I propose the following diagram. This is only regarding the frontend that is going to be developed in Swift and Flutter.


![Image](https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/assets/78159223/36039784-6327-4100-840c-7407f4f68947)

**Comment by jfpatino01** [comment]
I would move reports to the left and move police crime reports under another class, maybe with them as inherting from a main class containing all reports. This is because the users should access all reports, possibly only the statistics, regardless of if they made it or not. Also, I think reports and police crime reports should include locations and so should hte itinerary and trip, this way the app only requests information that is useful locally as to deal with possible memory issues and also reduce amount of data loaded at a time.

**Comment by JMarts32** [comment]
Corrected version
![Image](https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/assets/78159223/62ea4884-6f24-44ce-bd87-7bda0b345ed2)
